# Javascript Node CircleCI 2.0 configuration file
#custom
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  react:ci-poc/reactjs@0.03
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:16.20.0


    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install

     
      
      # run tests!
      - run: npm test



